name: damgerepoert
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  # Essential Flutter packages
  cupertino_icons: ^1.0.8
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  firebase_storage: ^12.3.7
  get: ^4.6.6
  
  cloud_firestore: ^5.5.1
  shared_preferences: ^2.3.3
  google_fonts: ^6.2.1
  gap: ^3.0.1
  mask_text_input_formatter: ^2.9.0
  google_nav_bar: ^5.0.7
  flutter_svg: ^2.0.16
  image_picker: ^1.1.2
  supabase_flutter: ^2.8.1
  dio: ^5.7.0
  geolocator: ^13.0.2
  flutter_google_places_hoc081098: ^2.0.0
  location: ^7.0.1
  google_maps_flutter: ^2.10.0
  google_maps_webservice: ^0.0.20-nullsafety.5
  carousel_slider: ^5.0.0

  # Removed google_maps_webservice to avoid conflicts
  # google_maps_webservice: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

dependency_overrides:
  http: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
