// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzlqLyDvVMTyuPTbK-TFxAtvEEbcLA3L4',
    appId: '1:1082140399037:web:a6f21b8c656e02c747eed4',
    messagingSenderId: '1082140399037',
    projectId: 'damgereport',
    authDomain: 'damgereport.firebaseapp.com',
    storageBucket: 'damgereport.firebasestorage.app',
    measurementId: 'G-5L517FQBMK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBH12h5WQnVbQnMQWWNxoo54cBRb_qNglM',
    appId: '1:1082140399037:android:10760b9737ba3f6447eed4',
    messagingSenderId: '1082140399037',
    projectId: 'damgereport',
    storageBucket: 'damgereport.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7JwMwV5405ry5MZ4aafJJjEHRIt2pcTk',
    appId: '1:1082140399037:ios:a2116c749ee4378b47eed4',
    messagingSenderId: '1082140399037',
    projectId: 'damgereport',
    storageBucket: 'damgereport.firebasestorage.app',
    iosBundleId: 'com.example.damgerepoert',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7JwMwV5405ry5MZ4aafJJjEHRIt2pcTk',
    appId: '1:1082140399037:ios:a2116c749ee4378b47eed4',
    messagingSenderId: '1082140399037',
    projectId: 'damgereport',
    storageBucket: 'damgereport.firebasestorage.app',
    iosBundleId: 'com.example.damgerepoert',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzlqLyDvVMTyuPTbK-TFxAtvEEbcLA3L4',
    appId: '1:1082140399037:web:d6d181b8fbbf1f7247eed4',
    messagingSenderId: '1082140399037',
    projectId: 'damgereport',
    authDomain: 'damgereport.firebaseapp.com',
    storageBucket: 'damgereport.firebasestorage.app',
    measurementId: 'G-3T0W2MPSGK',
  );

}